### ISSUE TITLE
Bug - Api endpoints querying every project multiple times per page view.

### ISSUE THREAD

**Issue by baktun14** [web3index/web3index-org#47]
Hi, we implemented the Akash integration with an api endpoint and it seems like your api is calling all the projects for every endpoint and spamming our api. 

![image](https://user-images.githubusercontent.com/15185355/135773841-401c1817-b42c-40de-95e7-d7ae670fa8e5.png)

Would it be possible also to cache the api integrations response in your backend to not have to query the projects every page view?

**Comment by adamsoffer** [comment]
Hey @baktun14 - the Akash API results now get cached in a postgres database every hour. Resolved in PR #53
